package io.left.meshenger.Models;

import android.os.Parcel;
import android.os.Parcelable;

import java.text.SimpleDateFormat;
import java.util.Date;


public class Message implements Parcelable {
    private String message;
    private Date date;
    private User sender;
    private User recipient;
    private boolean isMyMessage;

    private static SimpleDateFormat dateFormat = new SimpleDateFormat("hh:mm a yyyy-M-dd");

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public User getSender() {
        return sender;
    }

    public void setSender(User sender) {
        this.sender = sender;
    }

    public User getRecipient() {
        return recipient;
    }

    public void setRecipient(User recipient) {
        this.recipient = recipient;
    }

    public boolean isMyMessage() {
        return isMyMessage;
    }

    public void setIsMyMessage(boolean isMyMessage) {
        this.isMyMessage = isMyMessage;
    }

    /**
     * Constructor.
     * @param message message sender want to send
     * @param user User data of the sender
     * @param isMyMessage boolean
     */
    public Message(String message, User user, boolean isMyMessage) {
        this.message = message;
        this.sender = user;
        this.isMyMessage = isMyMessage;
        this.date = new Date();
    }

    /**
     * Converts local {@link Date} to a String with {@link this#dateFormat}.
     *
     * @return formatted date string
     */
    public String getDateAsString() {
        return dateFormat.format(date);
    }

    /**
     * Instantiates a {@link Message }from a {@link Parcel}.
     * <p>
     *     Generated by Android Studio.
     * </p>
     * @param in Parcel to parse.
     */
    protected Message(Parcel in) {
        message = in.readString();
        date = new Date(in.readLong());
        sender = in.readParcelable(User.class.getClassLoader());
        recipient = in.readParcelable(User.class.getClassLoader());
        isMyMessage = in.readByte() != 0;
    }

    // Required by Parcelable, created by Android Studio.
    public static final Creator<Message> CREATOR = new Creator<Message>() {
        /**
         * {@inheritDoc}.
         */
        @Override
        public Message createFromParcel(Parcel in) {
            return new Message(in);
        }

        /**
         * {@inheritDoc}.
         */
        @Override
        public Message[] newArray(int size) {
            return new Message[size];
        }
    };

    /**
     * {@link Parcelable} default.
     * @return 0
     */
    @Override
    public int describeContents() {
        return 0;
    }

    /**
     * Writes contents to a parcel.
     * <p>
     *     Generated by Android Studio.
     * </p>
     * @param dest parcel to write to
     * @param flags flags, I guess
     */
    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(message);
        dest.writeLong(date.getTime());
        dest.writeParcelable(sender, flags);
        dest.writeParcelable(recipient, flags);
        dest.writeByte((byte) (isMyMessage ? 1 : 0));
    }
}